import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { listEtapas, listOportunidades } from "../services/oportunidades.js";
import { useAuth } from "../contexts/AuthContext.js";
import { ERRO_SESSAO_EXPIRADA } from "../services/auth.js";
const META_CARROS_MES = 30;
// Tela inicial — visão rápida do funil, antes de entrar no Pipeline.
export function Dashboard({ onIrPipeline }) {
    const { usuario, idToken, logout } = useAuth();
        const [etapas, setEtapas] = useState([]);
            const [oportunidades, setOportunidades] = useState([]);
                const [carregando, setCarregando] = useState(true);
                    const [erro, setErro] = useState(null);
                        useEffect(() => {
                                if (!idToken)
                                            return;
                                                    Promise.all([listEtapas(idToken), listOportunidades(idToken)])
                                                                .then(([etapasResp, oportunidadesResp]) => {
                                                                            setEtapas([...etapasResp].sort((a, b) => a.ordem - b.ordem));
                                                                                        setOportunidades(oportunidadesResp);
                                                                                                })
                                                                                                            .catch((e) => {
                                                                                                                        // Bug corrigido em 2026-08-02 (achado ao implementar o Passo 4):
                                                                                                                                    // este catch não existia — qualquer falha na leitura ficava como
                                                                                                                                                // promise rejeitada sem tratamento, e a tela nunca saía de
                                                                                                                                                            // "carregando" (visto em produção como "Uncaught (in promise)"
                                                                                                                                                                        // no console). Sessão expirada força logout (volta para a tela
                                                                                                                                                                                    // de login); outros erros mostram uma mensagem em vez de travar.
                                                                                                                                                                                                if (e instanceof Error && e.message === ERRO_SESSAO_EXPIRADA) {
                                                                                                                                                                                                                logout();
                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        setErro("Não foi possível carregar o dashboard. Tente recarregar a página.");
                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                            .finally(() => setCarregando(false));
                                                                                                                                                                                                                                                                                }, [idToken, logout]);
                                                                                                                                                                                                                                                                                    if (carregando)
                                                                                                                                                                                                                                                                                            return _jsx("p", { className: "pipeline-loading", children: "Carregando dashboard..." });
                                                                                                                                                                                                                                                                                                if (erro)
                                                                                                                                                                                                                                                                                                        return _jsx("p", { className: "pipeline-loading", children: erro });
                                                                                                                                                                                                                                                                                                            const ativas = oportunidades.filter((o) => {
                                                                                                                                                                                                                                                                                                                    const etapa = etapas.find((e) => e.id === o.etapaId);
                                                                                                                                                                                                                                                                                                                            return etapa?.tipo === "ativa";
                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                    const vendidas = oportunidades.filter((o) => {
                                                                                                                                                                                                                                                                                                                                            const etapa = etapas.find((e) => e.id === o.etapaId);
                                                                                                                                                                                                                                                                                                                                                    return etapa?.tipo === "ganho";
                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                            const perdidas = oportunidades.filter((o) => {
                                                                                                                                                                                                                                                                                                                                                                    const etapa = etapas.find((e) => e.id === o.etapaId);
                                                                                                                                                                                                                                                                                                                                                                            return etapa?.tipo === "perdido";
                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                    const totalFechadas = vendidas.length + perdidas.length;
                                                                                                                                                                                                                                                                                                                                                                                        const taxaConversao = totalFechadas > 0 ? Math.round((vendidas.length / totalFechadas) * 100) : 0;
                                                                                                                                                                                                                                                                                                                                                                                            const progressoMeta = Math.min(100, Math.round((vendidas.length / META_CARROS_MES) * 100));
                                                                                                                                                                                                                                                                                                                                                                                                return (_jsxs("div", { className: "dashboard", children: [_jsxs("h1", { children: ["Olá, ", usuario?.nome ?? "—"] }), _jsx("p", { className: "dashboard__subtitulo", children: "Resumo rápido do funil comercial de hoje." }), _jsxs("div", { className: "dashboard__cards", children: [_jsxs("div", { className: "dashboard__card", children: [_jsx("span", { className: "dashboard__card-label", children: "Oportunidades ativas" }), _jsx("strong", { className: "dashboard__card-valor", children: ativas.length })] }), _jsxs("div", { className: "dashboard__card", children: [_jsx("span", { className: "dashboard__card-label", children: "Vendas no mês" }), _jsxs("strong", { className: "dashboard__card-valor", children: [vendidas.length, " ", _jsxs("small", { children: ["/ ", META_CARROS_MES] })] }), _jsx("div", { className: "dashboard__barra", children: _jsx("div", { className: "dashboard__barra-preenchida", style: { width: `${progressoMeta}%` } }) })] }), _jsxs("div", { className: "dashboard__card", children: [_jsx("span", { className: "dashboard__card-label", children: "Taxa de conversão" }), _jsxs("strong", { className: "dashboard__card-valor", children: [taxaConversao, "%"] })] }), _jsxs("div", { className: "dashboard__card", children: [_jsx("span", { className: "dashboard__card-label", children: "Perdidas no período" }), _jsx("strong", { className: "dashboard__card-valor", children: perdidas.length })] })] }), _jsx("button", { className: "dashboard__cta", onClick: onIrPipeline, children: "Ver Pipeline completo →" })] }));
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                
