import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useRef, useState } from "react";
import { useAuth } from "../contexts/AuthContext.js";
import { autenticarComGoogle, mensagemErroLogin } from "../services/auth.js";
// Tela de Login (Sign in with Google) — Passo 4 do roadmap, autorizado
// pelo CPO em 2026-08-02.
//
// Usa o Google Identity Services (GIS) direto via <script> no HTML
// publicado (ver index-cdn.html) — não é um pacote npm, é a forma
// recomendada pelo próprio Google para integrar sem framework, e já é
// compatível com a decisão de usar CDN só no preview (a versão oficial
// com Vite pode trocar para @react-oauth/google sem mudar o backend).
const GOOGLE_CLIENT_ID = "736212830198-6fkfhrf2fd54k5ik510dlgek3js12o7g.apps.googleusercontent.com";
export function Login() {
    const { login } = useAuth();
        const botaoRef = useRef(null);
            const [erro, setErro] = useState(null);
                const [entrando, setEntrando] = useState(false);
                    useEffect(() => {
                            if (!GOOGLE_CLIENT_ID) {
                                        setErro("VITE_GOOGLE_CLIENT_ID não configurado — login com Google indisponível.");
                                                    return;
                                                            }
                                                                    if (!window.google) {
                                                                                setErro("Não foi possível carregar o login do Google. Verifique sua conexão e recarregue a página.");
                                                                                            return;
                                                                                                    }
                                                                                                            window.google.accounts.id.initialize({
                                                                                                                        client_id: GOOGLE_CLIENT_ID,
                                                                                                                                    callback: async (response) => {
                                                                                                                                                    setEntrando(true);
                                                                                                                                                                    setErro(null);
                                                                                                                                                                                    try {
                                                                                                                                                                                                        const { usuario, sessionToken } = await autenticarComGoogle(response.credential);
                                                                                                                                                                                                                            login(sessionToken, usuario);
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            catch (e) {
                                                                                                                                                                                                                                                                                setErro(mensagemErroLogin(e));
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                finally {
                                                                                                                                                                                                                                                                                                                                    setEntrando(false);
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                if (botaoRef.current) {
                                                                                                                                                                                                                                                                                                                                                                                            window.google.accounts.id.renderButton(botaoRef.current, {
                                                                                                                                                                                                                                                                                                                                                                                                            theme: "outline",
                                                                                                                                                                                                                                                                                                                                                                                                                            size: "large",
                                                                                                                                                                                                                                                                                                                                                                                                                                            text: "signin_with",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            locale: "pt-BR",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, [login]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (_jsx("main", { style: { display: "grid", placeItems: "center", height: "100vh" }, children: _jsxs("div", { style: { display: "flex", flexDirection: "column", alignItems: "center", gap: 16 }, children: [_jsx("h1", { style: { marginBottom: 0 }, children: "Companycar CRM" }), _jsx("p", { style: { margin: 0, color: "var(--cor-texto-suave)" }, children: "Entre com sua conta Google cadastrada." }), _jsx("div", { ref: botaoRef }), entrando && _jsx("p", { style: { margin: 0 }, children: "Entrando…" }), erro && _jsx("p", { style: { margin: 0, color: "var(--cor-primaria-escura)" }, children: erro })] }) }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
